import Head from "next/head";
import React, { useState } from "react";
import styles from "../styles/Home.module.css";
import { WeatherForm } from "../components/WeatherForm";
import { ListDays } from "../components/ListDays";

export default function Home() {
  const [title, setTitle] = useState("");
  const [days, setDays] = useState([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Write a city</h1>
        <h6>US and MX only</h6>

        <WeatherForm setDays={setDays} setTitle={setTitle} />

        <ListDays days={days} title={title} />
      </main>
    </div>
  );
}
